MCKIN-12153 AF#41-Simulated_Chat-Inform assistive technologies of changes in content
open-craft/xblock-chat pull request #34
Opened 2019-11-06 13:49 UTC by nasirhjafri

## [MCKIN-12123](https://edx-wiki.atlassian.net/browse/MCKIN-12123)

AF#41-Simulated_Chat-Inform assistive technologies of changes in content

2019-11-13 20:16 UTC, nasirhjafri commented
@Agrendalath  @xitij2000  This PR was also part of the tickets sent for review last sprint. Please review.

2019-11-15 06:40 UTC, xitij2000 commented
@nasirhjafri Just pinging me is sufficient. I think our sprints may be misaligned, I got the tickets for review in the current sprint, and as such they are scheduled for review next sprint, starting this coming monday.

2019-11-26 10:11 UTC, nasirhjafri commented
@xitij2000 Reminder: to review this one, thanks.

2019-11-26 14:27 UTC, lgp171188 commented
@nasirhjafri, I am reviewing this today and hope to have a review pass done before my EOD today.

2019-11-26 17:49 UTC, lgp171188 commented
@nasirhjafri, I tested it on the Ironwood devstack and found that this PR only adds a highlight (through a dotted border for the whole chat block and not for the individual messages. Should this also be tested in the solutions devstack and the custom LMS frontend?

2019-11-26 18:55 UTC, lgp171188 commented
@nasirhjafri, my previous comment was due to misunderstanding the purpose of this PR and the changes made.

Apart from checking that the `aria-live` attribute is present with the `"polite"` value, is there any way to test that this works okay in screen readers?

2019-11-26 19:01 UTC, nasirhjafri commented
@lgp171188 No, it only needs to be tested with screen readers.

2019-11-28 11:02 UTC, lgp171188 commented
@nasirhjafri, I will test with a screen reader today and post an update.

2019-11-29 12:03 UTC, Agrendalath requested changes

2019-11-29 12:03 UTC, Agrendalath commented on setup.py
> +    version='0.2.4',
Please bump the version to `0.2.5`.

2019-11-30 04:34 UTC, lgp171188 commented
@nasirhjafri, I finally tested this using the "Narrator" screen reader app on Windows 10 and verified that the changes work okay, except for a small issue. All the messages from the bot are read out loud except the last one about the README file. However, it looks like the `<div>` containing that message is not structured differently from the other divs that the app read out aloud. Can you test this and confirm if you see the same issue?

Also can you resolve the conflicts and also bump the version as requested by @Agrendalath?

2019-12-02 09:39 UTC, nasirhjafri commented
@lgp171188 Sure lemme test on my side. I've rebased the branch though.

2019-12-02 13:42 UTC, lgp171188 commented
> @lgp171188 Sure lemme test on my side. I've rebased the branch though.

@nasirhjafri, did you encounter the same issue I reported in an earlier comment?

2019-12-03 11:12 UTC, nasirhjafri commented
@lgp171188 It was reading all of the messages. After rebasing from master (changes from https://github.com/open-craft/xblock-chat/pull/35), it started to read messages twice. I've fixed that, rest is good.

2019-12-03 17:16 UTC, lgp171188 commented
@nasirhjafri, thanks for the update. I am on leave this week and hence will ask a colleague to do a final check and merge this if everything is okay.

2019-12-03 17:19 UTC, lgp171188 commented
@giovannicimolin, can you do a quick check of the discussion on this PR, check and test it and approve this PR if everything is okay?

2019-12-04 12:54 UTC, giovannicimolin approved these changes
:+1:

- [x] I tested this:
1. Installed this on an Ironwood devstack.
2. Setup the xblock on the demo course.
3. Checked that the chat messages were read correctly by a screen reader :heavy_check_mark: 
   I used `Pericles` chrome browser extension to perform the tests, targeting the reader to read the contents inside the chat box.
- [x] I read through the code
- [x] I checked for accessibility issues: This fixes an accessibility issue.
- [ ] ~~Includes documentation~~ NA

2019-12-04 12:55 UTC, merged

2019-12-04 12:56 UTC, giovannicimolin commented
@nasirhjafri I've merged the PR and tagged a new release from the latest `master`. CC @lgp171188

2019-12-04 13:10 UTC, nasirhjafri commented
Great, thanks for reviewing @giovannicimolin @lgp171188